### ISSUE TITLE
Write styles for dark theme

### ISSUE THREAD

**Issue by rahulpanchal0106** [rahulpanchal0106/Socio-Web-Client#1]
I need someone to write CSS for the Dark theme mode.

**Comment by Abhinav384** [comment]
Hi @rahulpanchal0106,
I've primarily worked with Node.js, but I'm really eager to dive into front-end development as well. Would there be an opportunity for me to contribute to your app? I'd love to get involved!

**Comment by Abhinav384** [comment]
Also, this is my first time contributing to an open-source project, so I might need a bit of guidance to ensure my code is up to snuff. I appreciate your patience and support as I get the hang of it!

**Comment by rahulpanchal0106** [comment]
Hi @Abhinav384,

Yeah, sure! It would be great to work with you. 

There are also many other issues that aren’t listed in the issues section. If you’re interested in diving deeper or tackling something specific, just let me know, and I can guide you to some areas that need attention. Looking forward to your contributions!

**Comment by rahulpanchal0106** [comment]
I'll provide the development server link with db, so that you won't have to worry about dummy data and server-side.

**Comment by Abhinav384** [comment]
Absolutely, if there are any issues related to the back-end or database, I'd be excited to address them. Back-end development is where my expertise really shines, so it's right up my alley!

**Comment by Abhinav384** [comment]
Hi @rahulpanchal0106,
I have a quick question. I noticed there are two index.html files in the repository: one in the dist folder and another one at the root level. Could you please clarify the purpose of each file and if there's a specific reason for having both?
![Screenshot 2024-08-21 235221](https://github.com/user-attachments/assets/22cd4c96-efb0-4612-b834-1974c6713624)

**Comment by rahulpanchal0106** [comment]
The /dist directory is a build of the project. Vite compile and bundle our code into optimized files HTML, CSS, and JS, which are then placed in the /dist directory.

So its like an optimized version of our react code, ready to be published.

Normally Dist directory is not needed in development environment, its manly used on deployment side to ensure high performance. 

You can safely remove the whole Dist directory or ignore it.

And that index.html below is our actual development file, though we only work on src folder, where all the react components resides.

**Comment by Abhinav384** [comment]
@rahulpanchal0106 I’ve created a new branch and added a dark mode theme to the main navigation bar. Apologies for the delay in my response; I’m currently interning and not working on this project regularly.

**Comment by rahulpanchal0106** [comment]
You did a great job adding the toggle button and the core functionality for theme toggling.
Awesome contribution! 🙌
